## Q3 & Q4

Both Q3 and Q4 are solved in this one .ipynb file. 

In [66]:
#X is input and y represents class
import numpy as np
#                bias        x1         x2
X = np.array([[1,1,1,1], [0,0,1,1], [0,1,0,1]])
y= np.array([-1,1,1,1])

In [67]:
X

array([[1, 1, 1, 1],
       [0, 0, 1, 1],
       [0, 1, 0, 1]])

In [68]:
y=y.reshape(1,4)
y

array([[-1,  1,  1,  1]])

In [69]:
#no of neurons in hidden layer(excluding bias)
m = 3

In [70]:
#initializing weights
w1 = np.array([[0.1]*m]*3)
w1

array([[0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1]])

In [92]:
#initializing weights
w2 = np.array([0.1]*(m+1))
w2=w2.reshape((m+1),1)
w2

array([[0.1],
       [0.1],
       [0.1],
       [0.1]])

In [72]:
def forward(X,y,w1,w2,m):
    signal_layer1 = (w1.T).dot(X)
    lay=(m+1,y.size)
    output_layer1 = np.empty(lay)
    for i in range(y.size):
        output_layer1[0][i]=1
    for j in range(m):
        output_layer1[j+1]=np.tanh(signal_layer1[j])
    final_signal = (w2.T).dot(output_layer1)
    final_output = np.tanh(final_signal)
    return final_output,output_layer1,signal_layer1

In [73]:
def backward(X,y,final_output,w1,w2,output_layer1,signal_layer1):
    delta2 = 2*(y-final_output)*(1-(final_output*final_output))
    g=w2.dot(delta2)
    delta1= (1-(np.tanh(signal_layer1)*np.tanh(signal_layer1)))*(g[1:])
    d_w1=X.dot(delta1.T)
    d_w2=output_layer1.dot(delta2.T)
    return d_w1,d_w2

In [74]:
#updating the weights using the gradients computed from 'backward' method and a learning rate of 0.01 - Gradient descent
epochs=0
while(epochs<10000):
    final_output,output_layer1,signal_layer1=forward(X,y,w1,w2,m)
    d_w1,d_w2=backward(X,y,final_output,w1,w2,output_layer1,signal_layer1)
    w1+=0.01*d_w1
    w2+=0.01*d_w2
    epochs+=1

In [75]:
#computing the output after learning
signal_layer1 = (w1.T).dot(X)
lay=(m+1,y.size)
output_layer1 = np.empty(lay)
for i in range(y.size):
    output_layer1[0][i]=1
for j in range(m):
    output_layer1[j+1]=np.tanh(signal_layer1[j])
final_signal = (w2.T).dot(output_layer1)
final_output = np.tanh(final_signal)
print(final_output)

[[-0.98277343  0.98826126  0.98826126  0.99975704]]


In [76]:
#actual labels
y

array([[-1,  1,  1,  1]])

In [77]:
#calculating ein
error=(y-final_output)*(y-final_output)
ein=0
for x in error[0]:
    ein+=x
ein=ein/y.size
ein

0.0001431024386477165

Below is Stochastic Gradient Descent

In [84]:
#initializing weights
w1 = np.array([[0.1]*m]*3)
w1

array([[0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1]])

In [87]:
#initializing weights
w2 = np.array([0.1]*(m+1))
w2=w2.reshape(4,1)
w2

array([[0.1],
       [0.1],
       [0.1],
       [0.1]])

In [88]:
#updating the weights using the gradients computed from 'backward' method and a learning rate of 0.01 - Stochastic gradient descent
epochs=0
lay=(3,1)
temp=np.empty(lay)
while(epochs<10000): 
    i=np.random.randint(0, y.size-1) 
    temp[0]=X[0][i]
    temp[1]=X[1][i]
    temp[2]=X[2][i]
    temp_y=y[0][i]
    temp_y=temp_y.reshape(1,1)
    final_output,output_layer1,signal_layer1=forward(temp,temp_y,w1,w2,m)
    d_w1,d_w2=backward(temp,temp_y,final_output,w1,w2,output_layer1,signal_layer1)
    w1+=0.01*d_w1
    w2+=0.01*d_w2
    epochs+=1

In [89]:
#computing the output after learning
signal_layer1 = (w1.T).dot(X)
lay=(m+1,y.size)
output_layer1 = np.empty(lay)
for i in range(y.size):
    output_layer1[0][i]=1
for j in range(m):
    output_layer1[j+1]=np.tanh(signal_layer1[j])
final_signal = (w2.T).dot(output_layer1)
final_output = np.tanh(final_signal)
print(final_output)

[[-0.96754216  0.97737346  0.97727463  0.99937586]]


In [90]:
#actual labels
y

array([[-1,  1,  1,  1]])

In [91]:
#calculating ein
error=(y-final_output)*(y-final_output)
ein=0
for x in error[0]:
    ein+=x
ein=ein/y.size
ein

0.0005205760287229035